// Generated by `npx @convex-dev/auth` — named export to satisfy
// import/no-anonymous-default-export (regenerating rewrites this file).
const authConfig = {
  providers: [
    {
      domain: process.env.CONVEX_SITE_URL,
      applicationID: "convex",
    },
  ],
};

export default authConfig;
